# Generated by Django 3.0.6 on 2020-09-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapisy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uczen',
            name='jezyk_obcy',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
