# Generated by Django 3.0.6 on 2020-10-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapisy', '0002_uczen_jezyk_obcy'),
    ]

    operations = [
        migrations.AddField(
            model_name='uczen',
            name='passcode',
            field=models.CharField(default=12345678, max_length=8),
            preserve_default=False,
        ),
    ]
