# Generated by Django 3.0.6 on 2020-10-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zapisy', '0003_uczen_passcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uczen',
            name='jezyk_obcy',
        ),
    ]
